// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bnb`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MatchParameters`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Perform Coinselection via Branch And Bound algorithm.
Future<SelectionOutput> selectCoinBnb({
  required List<OutputGroup> inputs,
  required CoinSelectionOpt options,
}) => RustLib.instance.api.crateAlgorithmsBnbSelectCoinBnb(
  inputs: inputs,
  options: options,
);
