// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Performs coin selection using the First-In-First-Out (FIFO) algorithm.
///
/// Returns `NoSolutionFound` if no solution is found.
Future<SelectionOutput> selectCoinFifo({
  required List<OutputGroup> inputs,
  required CoinSelectionOpt options,
}) => RustLib.instance.api.crateAlgorithmsFifoSelectCoinFifo(
  inputs: inputs,
  options: options,
);
